name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate config
        run: |
          mkdir -p public
          echo "const API_KEY = atob('${{ secrets.API_KEY_BASE64 }}');" > public/config.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
