name: Generate Config
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate config file
      run: |
        echo "const API_KEY = '${{ secrets.API_KEY }}';" > public/config.js
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git commit -m "Update config.js" || exit 0
        git push
