name: Use API Key
on: [push]

jobs:
  test-api-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node script.js
